#ifndef __HORSERACEERRORS_H_
#define __HORSERACEERRORS_H_

enum HRErrorCode{
	HR_SUCCESS = 0,
	HR_NO_ACTIVE_RACE,
	HR_INVALID_RACE,
	HR_INVALID_HORSE,
	HR_INVALID_HOUSE_TAKE,
	HR_INVALID_BET,
	HR_INVALID_NAME,
	HR_UNIMPLEMENTED,
	HR_DISCONNECTED
};


#endif